'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const data=window.CLASS_DATA, config=window.APP_CONFIG;
const subjects=[
 {id:'toan',name:'Toán',icon:'π',color:'#295eb1',tint:'#eaf0ff',desc:'Đề cương để đọc, tải về và tự ôn tập.',resources:[['toan-dc','Đề cương Toán','toan-de-cuong.pdf','PDF']]},
 {id:'van',name:'Ngữ Văn',icon:'V',color:'#a34956',tint:'#faedf0',desc:'Nắm nội dung đề cương, thực hành với đề luyện thêm.',resources:[['van-dc','Đề cương Ngữ Văn','van-de-cuong.docx','DOCX'],['van-lt','Đề luyện thêm','van-de-luyen.pdf','PDF']]},
 {id:'anh',name:'Tiếng Anh',icon:'Aa',color:'#946624',tint:'#fbf3e4',desc:'Đề cương ôn tập và đề tham khảo số 2.',resources:[['anh-dc','Đề cương Tiếng Anh','anh-de-cuong.docx','DOCX'],['anh-de2','Đề tham khảo số 2','anh-de-2.docx','DOCX']]},
 {id:'li',name:'Vật Lí',icon:'v/t',color:'#345dc5',tint:'#e9efff',desc:'Làm 25 câu trực tiếp và đối chiếu đáp án sau khi nộp.',resources:[['li-de','Đề Vật Lí · Mã 1104','li-de-1104.docx','DOCX']]},
 {id:'hoa',name:'Hoá học',icon:'H₂',color:'#7c4db2',tint:'#f1eafb',desc:'Đề cương và hai bài luyện tập từ giáo viên bộ môn.',resources:[['hoa-dc','Đề cương Hoá học','hoa-de-cuong.docx','DOCX'],['hoa-c1','Luyện tập Chương 1','https://youngtest.vn/quiz/ukkJZ9','YOUNGTEST'],['hoa-c2','Luyện tập Chương 2','https://youngtest.vn/quiz/xfxMyp','YOUNGTEST']]},
 {id:'tin',name:'Tin học',icon:'</>',color:'#177f95',tint:'#e6f5f8',desc:'Tải đề cương và chủ động ôn lại kiến thức.',resources:[['tin-dc','Đề cương Tin học','tin-de-cuong.docx','DOCX']]}
];
let teacherRoster=[],student=null,pin='',selected=null,quiz=null,timer=null,teacherToken='',events=[],toastTimer,renderId=0;
const date=v=>new Date(v).toLocaleString('vi-VN');
function toast(s){$('#toast').textContent=s;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',6500)}
function connectionNotice(){return config.apiUrl?'':'<div class="notice">Chế độ xem thử: chưa kết nối nơi lưu kết quả chung. Em có thể xem tài liệu và luyện Lí, nhưng kết quả chưa được gửi cho GVCN.</div>'}
async function api(action,payload={}){
 if(!config.apiUrl)throw Error('Chưa kết nối nơi lưu dữ liệu chung. Kết quả chưa được gửi cho GVCN.');
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),25000);
 try{const res=await fetch(config.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload}),signal:controller.signal});if(!res.ok)throw Error('Máy chủ chưa phản hồi. Vui lòng thử lại.');const result=await res.json();if(!result.ok)throw Error(result.error||'Không thể lưu dữ liệu.');return result;}catch(e){if(e.name==='AbortError')throw Error('Kết nối quá thời gian. Chưa xác nhận đã lưu, hãy thử lại.');throw e;}finally{clearTimeout(timeout)}
}
function credentials(){return {studentId:student?.id,pin}}
function openStudents(){if(quiz&&!quiz.saved){if(!confirm('Bài Lí hiện tại chưa được lưu cho GVCN. Đổi học sinh sẽ đóng bài này. Em vẫn muốn đổi?'))return;saveDraft();quiz=null;}$('#studentAuth').hidden=true;$('#studentList').hidden=false;$('#studentError').textContent='';$('#studentsDialog').showModal()}
function setStudent(s,p){quiz=null;student=s;pin=p;events=[];$('#identity').textContent=s.name;$('#studentsDialog').close();render();toast('Đã chọn '+s.name)}
$('#identity').onclick=openStudents;$('#closeStudents').onclick=()=>$('#studentsDialog').close();
$('#studentList').innerHTML=data.students.map(s=>`<button class="studentbtn" data-student="${s.id}"><span>${s.id}</span>${esc(s.name)}</button>`).join('');
$('#studentList').onclick=e=>{const b=e.target.closest('[data-student]');if(!b)return;selected=data.students.find(s=>s.id===b.dataset.student);if(!config.apiUrl){setStudent(selected,'');return}$('#studentList').hidden=true;$('#studentAuth').hidden=false;$('#chosenName').textContent=selected.name;$('#studentPin').value='';$('#studentPin').focus()};
$('#studentAuth').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const p=$('#studentPin').value.trim();const logged=await api('login',{studentId:selected.id,pin:p});setStudent({id:selected.id,name:logged.name},p)}catch(err){$('#studentError').textContent=err.message}finally{b.disabled=false}};
function needStudent(){if(!student){openStudents();return false}return true}
function home(){return `<section class="welcome"><div><span class="eyebrow">LỚP 10IT · GIỮA HỌC KÌ I</span><h1>10IT - Ôn tập giữa Học Kì I</h1><p>${student?'Chào '+esc(student.name)+'. Chọn một môn để bắt đầu buổi ôn tập hôm nay.':'Một nơi cho đề cương, tài liệu và bài luyện của lớp mình. Chọn mã học sinh của em rồi bắt đầu ôn tập.'}</p><button class="primary" data-action="choose">${student?'Đổi học sinh':'Chọn mã để vào học'}</button></div><div class="welcome-side"><strong>16 <span style="font-size:18px;font-weight:400">học sinh</span></strong><p>6 môn học · 1 mục tiêu</p><small>Ôn từng phần, chắc từng bước.</small></div></section>${connectionNotice()}<div class="sectionhead"><h2>Hôm nay em ôn môn nào?</h2><span class="pill">Tài liệu từ giáo viên</span></div><section class="subjects">${subjects.map(s=>`<article class="subject ${s.id==='li'?'physics':''}" style="--accent:${s.color};--tint:${s.tint}"><div class="subject-top"><span class="subject-icon" aria-hidden="true">${esc(s.icon)}</span><span class="pill">${s.id==='li'?'Luyện trực tuyến':s.resources.length?'Tài liệu ôn tập':'Sẽ cập nhật'}</span></div><h3>${s.name}</h3><p>${s.desc}</p><div class="subject-foot"><span>${s.id==='li'?'25 câu · Mã 1104':s.resources.length?s.resources.length+' tài liệu / bài luyện':'Chưa có tài liệu'}</span><span>${s.id==='li'?'40 phút gợi ý':''}</span></div><a class="${s.id==='li'?'primary':'secondary'}" href="#subject/${s.id}">${s.resources.length?'Vào ôn tập':'Xem môn học'}</a></article>`).join('')}</section>`}
function subjectPage(id){const s=subjects.find(s=>s.id===id);if(!s)return home();return `<a class="back" href="#home">Quay lại các môn</a><span class="eyebrow" style="display:block">TÀI LIỆU & LUYỆN TẬP</span><h1>${s.name}</h1><p class="muted">${s.desc}</p>${connectionNotice()}${s.id==='li'?`<section class="panel"><span class="pill">LÀM TRỰC TIẾP TRÊN WEB</span><h2 style="margin-top:12px">Vật Lí 10 · Mã đề 1104</h2><p>25 câu trắc nghiệm · Thời gian gợi ý 40 phút. Nộp bài để xem đúng/sai và đáp án từ giáo viên. Đây là bài tự luyện, không phải bài kiểm tra lấy điểm.</p><button class="primary" data-action="startQuiz">Bắt đầu luyện tập</button></section>`:''}<div class="resources">${s.resources.map(r=>`<article class="resource"><div><span class="eyebrow">${r[3]}</span><h3>${r[1]}</h3><p>${r[3]==='YOUNGTEST'?'Bài luyện do giáo viên bộ môn cung cấp':'Giữ nguyên tài liệu giáo viên cung cấp'}</p></div><div class="resource-actions"><a href="${r[2]}" target="_blank" rel="noopener noreferrer" data-resource="${r[0]}">${r[3]==='YOUNGTEST'?'Mở bài luyện':'Mở / tải tài liệu'}</a><button class="secondary" data-complete="${r[0]}">Em đã ôn xong</button></div></article>`).join('')||'<div class="panel empty">Chưa có tài liệu.</div>'}</div>${s.id!=='li'&&s.resources.length?'<div class="notice">“Em đã ôn xong” là tự xác nhận của học sinh. Website không chấm bài trong file hoặc tự lấy điểm từ YoungTest.</div>':''}`}
async function record(kind,resource){if(!student)return false;await api('event',{...credentials(),eventId:crypto.randomUUID(),kind,resource});return true}
function draftKey(){return '10it-draft-1104-'+student.id}
function saveDraft(){if(quiz&&!quiz.submitted)try{sessionStorage.setItem(draftKey(),JSON.stringify(quiz))}catch{}}
function startQuiz(){if(!needStudent())return;let saved;try{saved=JSON.parse(sessionStorage.getItem(draftKey()))}catch{}quiz=saved&&Array.isArray(saved.answers)&&saved.answers.length===25?saved:{id:crypto.randomUUID(),answers:Array(25).fill(''),started:Date.now(),submitted:false};location.hash='quiz';render()}
function quizPage(){if(!quiz)return '<div class="panel empty"><h1>Bài luyện Vật Lí</h1><p>Chọn mã học sinh trước khi bắt đầu.</p><button class="primary" data-action="startQuiz">Bắt đầu luyện tập</button></div>';const n=quiz.answers.filter(Boolean).length;return `<a class="back" href="#subject/li">Quay lại môn Vật Lí</a><span class="eyebrow" style="display:block">VẬT LÍ · MÃ ĐỀ 1104</span><h1>${quiz.submitted?'Kết quả bài luyện':'Từng câu một, thật chắc kiến thức.'}</h1><p class="muted">${esc(student.name)} · 25 câu trắc nghiệm · Thời gian gợi ý 40 phút</p>${connectionNotice()}${quiz.submitted?`<section class="result"><strong>${quiz.correct}/25 câu đúng</strong><p>${25-quiz.correct} câu sai hoặc chưa trả lời · ${Math.floor(quiz.duration/60)} phút ${quiz.duration%60} giây</p><p id="saveStatus">${quiz.saved?'Đã lưu kết quả cho GVCN.':'Chưa gửi kết quả cho GVCN.'}</p><div class="actions">${!quiz.saved?'<button class="secondary" data-action="retrySave">Gửi lại kết quả</button>':''}<button class="secondary" data-action="redo">Luyện lại</button></div></section><div class="notice">Đáp án đối chiếu từ file giáo viên, mã 1104. Chưa có lời giải chi tiết. Đáp án không thay thế việc đọc lại kiến thức.</div>`:''}<div class="quiz-layout"><div class="quiz-main">${data.groups.map((g,i)=>`<section><h2>Nhóm câu ${g.questions[0].id}–${g.questions.at(-1).id}</h2><div class="intro">${g.intro}</div>${g.questions.map(q=>`<fieldset class="question" id="question-${q.id}" ${quiz.submitted?'disabled':''}><legend>Câu ${q.id}. ${q.text}</legend><div class="answers">${q.options.map(o=>`<label class="option ${quiz.submitted?(o.label===data.key[q.id-1]?'correct':quiz.answers[q.id-1]===o.label?'wrong':''):''}"><input type="radio" name="q${q.id}" value="${o.label}" data-q="${q.id}" ${quiz.answers[q.id-1]===o.label?'checked':''}><span><b>${o.label}.</b> ${o.text}</span></label>`).join('')}</div>${quiz.submitted?`<p class="review-note">${quiz.answers[q.id-1]===data.key[q.id-1]?'Đúng':'Chưa đúng'} · Em chọn: ${quiz.answers[q.id-1]||'Chưa trả lời'} · Đáp án: <strong>${data.key[q.id-1]}</strong></p>`:''}</fieldset>`).join('')}</section>`).join('')}</div><aside class="quiz-side panel"><span class="eyebrow">${quiz.submitted?'ĐÃ NỘP BÀI':'THỜI GIAN ĐÃ LÀM'}</span><div class="clock" id="clock">00:00</div><p class="muted" id="answeredCount">Đã trả lời ${n}/25 câu</p><div class="progressbar"><span id="quizBar" style="width:${n*4}%"></span></div><div class="qnav">${Array.from({length:25},(_,i)=>`<a href="#question-${i+1}" data-jump="${i+1}" class="${quiz.answers[i]?'answered':''}">${i+1}</a>`).join('')}</div>${!quiz.submitted?'<button class="primary" data-action="submitQuiz">Nộp bài & xem đáp án</button><small class="muted">Bản nháp chỉ được giữ trong tab này. Thời gian là gợi ý, không tự động nộp.</small>':'<a href="#progress">Xem tiến độ của em</a>'}</aside></div>`}
function clockTick(){if(!quiz||!$('#clock'))return;const secs=quiz.submitted?quiz.duration:Math.floor((Date.now()-quiz.started)/1000);$('#clock').textContent=String(Math.floor(secs/60)).padStart(2,'0')+':'+String(secs%60).padStart(2,'0')}
async function saveQuiz(){if(!quiz||quiz.saved)return;const q=quiz;try{const result=await api('submit',{...credentials(),attemptId:q.id,answers:q.answers,duration:q.duration});q.saved=true;q.correct=result.correct;if($('#saveStatus'))$('#saveStatus').textContent='Đã lưu kết quả cho GVCN.';toast('Đã lưu kết quả cho GVCN.')}catch(e){if($('#saveStatus'))$('#saveStatus').textContent=e.message;toast(e.message)}}
async function submitQuiz(){if(!quiz||quiz.submitted)return;const missing=quiz.answers.filter(a=>!a).length;if(!confirm(missing?`Còn ${missing} câu chưa trả lời. Em muốn nộp bài và xem đáp án?`:'Nộp bài và xem đáp án?'))return;quiz.duration=Math.max(0,Math.floor((Date.now()-quiz.started)/1000));quiz.correct=quiz.answers.filter((a,i)=>a===data.key[i]).length;quiz.submitted=true;try{sessionStorage.removeItem(draftKey())}catch{}render();window.scrollTo(0,0);await saveQuiz()}
function eventName(e){if(e.kind==='attempt')return 'Đã nộp bài Lí';if(e.kind==='complete')return 'Tự xác nhận đã ôn';if(e.kind==='login')return 'Vào học';return 'Đã mở tài liệu / link'}
const allResources=subjects.flatMap(s=>s.resources),resourceName=id=>allResources.find(r=>r[0]===id)?.[1]|| (id==='li-1104'?'Lí · Mã 1104':'Buổi học');
function historyRows(rows){return rows.length?`<div class="tablewrap"><table><thead><tr><th>Thời gian</th><th>Hoạt động</th><th>Nội dung</th><th>Kết quả</th></tr></thead><tbody>${rows.slice().reverse().map(e=>`<tr><td>${date(e.time)}</td><td>${eventName(e)}</td><td>${esc(resourceName(e.resource))}</td><td>${e.kind==='attempt'?`${e.correct}/25 câu đúng`: '—'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Chưa ghi nhận hoạt động.</p>'}
async function progressPage(rid){if(!student)return '<section class="panel empty"><h1>Tiến độ của em</h1><p>Chọn mã học sinh để xem quá trình ôn tập.</p><button class="primary" data-action="choose">Chọn mã học sinh</button></section>';$('#main').innerHTML=`<h1>Tiến độ của ${esc(student.name)}</h1>${connectionNotice()}<div class="panel" id="progressContent">Đang tải tiến độ…</div>`;try{const r=await api('progress',credentials());if(rid!==renderId)return;events=r.events;$('#progressContent').innerHTML=historyRows(events)}catch(e){if(rid===renderId)$('#progressContent').textContent=e.message}return null}
function teacherLogin(){return `<span class="eyebrow">DÀNH CHO GIÁO VIÊN</span><h1>Theo dõi lớp 10IT</h1><p class="muted">16 học sinh · Tiến độ theo môn · Các lượt làm bài Vật Lí</p>${connectionNotice()}<section class="panel" style="max-width:520px"><h2>Đăng nhập GVCN</h2><form id="teacherLogin"><label>Mã quản trị<input type="password" id="teacherPassword" autocomplete="current-password" required></label><button class="primary">Xem tiến độ lớp</button><p id="teacherError" role="alert"></p></form><p class="muted" style="font-size:14px">Kết quả cả lớp chỉ được tải sau khi xác thực mã quản trị.</p></section>`}
async function teacherDashboard(){if(!teacherToken)return;const rid=renderId;try{const r=await api('dashboard',{teacherToken});if(rid!==renderId)return;events=r.events;teacherRoster=r.students;const attempts=events.filter(e=>e.kind==='attempt');$('#main').innerHTML=`<div class="sectionhead"><div><span class="eyebrow">GVCN · LỚP 10IT</span><h1>Nhìn rõ từng bước tiến.</h1></div><div class="actions"><button class="secondary" data-action="refresh">Làm mới</button><button class="secondary" data-action="logout">Đăng xuất</button></div></div><div class="gridstats"><div class="stat"><strong>${new Set(events.map(e=>e.studentId)).size}/16</strong><span>Học sinh đã tham gia</span></div><div class="stat"><strong>${attempts.length}</strong><span>Lượt nộp bài Lí</span></div><div class="stat"><strong>${new Set(events.filter(e=>e.kind==='complete').map(e=>e.studentId+'|'+e.resource)).size}</strong><span>Tài liệu được tự xác nhận đã ôn</span></div></div><div class="notice">Lượt mở không chứng minh đã đọc hết. “Đã ôn” do học sinh tự xác nhận. Bài Lí được đối chiếu với key 1104.</div><section class="panel"><div class="sectionhead"><h2>16 học sinh</h2><button class="secondary" data-action="export">Xuất CSV</button></div><div class="tablewrap"><table><thead><tr><th>STT</th><th>Học sinh</th><th>Mở tài liệu</th><th>Tự xác nhận đã ôn</th><th>Lượt Lí</th><th>Lí gần nhất</th><th>Hoạt động gần nhất</th><th>Chi tiết</th></tr></thead><tbody>${teacherRoster.map(s=>{const es=events.filter(e=>e.studentId===s.id),qs=es.filter(e=>e.kind==='attempt');return `<tr><td>${s.id}</td><td>${esc(s.name)}</td><td>${es.filter(e=>e.kind==='open').length}</td><td>${new Set(es.filter(e=>e.kind==='complete').map(e=>e.resource)).size}/10</td><td>${qs.length}</td><td>${qs.length?qs.at(-1).correct+'/25':'Chưa làm'}</td><td>${es.length?date(es.at(-1).time):'Chưa tham gia'}</td><td><button class="secondary" data-detail="${s.id}">Xem</button></td></tr>`}).join('')}</tbody></table></div></section><section class="panel" id="studentDetail"><p class="muted">Nhấn “Xem” để theo dõi từng môn và từng lượt làm của một học sinh.</p></section>`;}catch(e){toast(e.message)}}
function studentDetail(id){const s=teacherRoster.find(s=>s.id===id);const rows=events.filter(e=>e.studentId===id);$('#studentDetail').innerHTML=`<h2>${esc(s.name)}</h2><div class="tablewrap"><table><thead><tr><th>Môn</th><th>Lượt mở</th><th>Tự xác nhận đã ôn</th></tr></thead><tbody>${subjects.map(sub=>{const ids=sub.resources.map(r=>r[0]);return `<tr><td>${sub.name}</td><td>${rows.filter(e=>e.kind==='open'&&ids.includes(e.resource)).length}</td><td>${new Set(rows.filter(e=>e.kind==='complete'&&ids.includes(e.resource)).map(e=>e.resource)).size}/${ids.length}</td></tr>`}).join('')}</tbody></table></div><h3 class="history">Lịch sử hoạt động</h3>${historyRows(rows)}${rows.filter(e=>e.kind==='attempt').map(e=>`<details class="panel"><summary>Lí · ${date(e.time)} · ${e.correct}/25 câu đúng</summary><p>Thời gian làm: ${Math.floor(e.duration/60)} phút ${e.duration%60} giây</p><div class="tablewrap"><table><thead><tr><th>Câu</th><th>Học sinh chọn</th><th>Đáp án</th><th>Kết quả</th></tr></thead><tbody>${(e.answers||[]).map((a,i)=>`<tr><td>${i+1}</td><td>${esc(a||'Bỏ trống')}</td><td>${data.key[i]}</td><td>${a===data.key[i]?'Đúng':'Sai / bỏ trống'}</td></tr>`).join('')}</tbody></table></div></details>`).join('')}`;$('#studentDetail').scrollIntoView({behavior:'smooth'})}
function exportCSV(){const rows=[['STT','Học sinh','Thời gian','Hoạt động','Nội dung','Câu đúng','Thời gian giây'],...events.map(e=>[e.studentId,teacherRoster.find(s=>s.id===e.studentId)?.name,date(e.time),eventName(e),resourceName(e.resource),e.correct??'',e.duration??''])];const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='10IT-tien-do.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function render(){const rid=++renderId;clearInterval(timer);const route=location.hash.slice(1)||'home';document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+route));let html;if(route==='home')html=home();else if(route.startsWith('subject/'))html=subjectPage(route.split('/')[1]);else if(route==='quiz'){html=quizPage();timer=setInterval(clockTick,1000)}else if(route==='progress')html=await progressPage(rid);else if(route==='teacher'){html=teacherLogin()}else html=home();if(html!==null&&rid===renderId)$('#main').innerHTML=html;clockTick();if(route==='teacher'&&teacherToken)teacherDashboard();}
window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#question-'))return;render()});
$('#main').addEventListener('change',e=>{if(e.target.matches('[data-q]')&&quiz&&!quiz.submitted){quiz.answers[+e.target.dataset.q-1]=e.target.value;saveDraft();const n=quiz.answers.filter(Boolean).length;$('#answeredCount').textContent=`Đã trả lời ${n}/25 câu`;$('#quizBar').style.width=n*4+'%';document.querySelector(`[data-jump="${e.target.dataset.q}"]`)?.classList.add('answered')}});
$('#main').addEventListener('submit',async e=>{if(e.target.id!=='teacherLogin')return;e.preventDefault();const b=e.submitter;b.disabled=true;try{const r=await api('teacherLogin',{password:$('#teacherPassword').value});teacherToken=r.token;await teacherDashboard()}catch(err){$('#teacherError').textContent=err.message}finally{b.disabled=false}});
$('#main').addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.jump){e.preventDefault();$('#question-'+b.dataset.jump)?.scrollIntoView({behavior:'smooth'});return}if(b.dataset.resource){if(!needStudent()){e.preventDefault();return}record('open',b.dataset.resource).then(()=>toast('Đã ghi nhận lượt mở.')).catch(err=>toast(err.message));return}if(b.dataset.complete){if(!needStudent())return;b.disabled=true;try{await record('complete',b.dataset.complete);b.textContent='Đã xác nhận';toast('Đã lưu xác nhận tự ôn cho GVCN.')}catch(err){toast(err.message)}finally{b.disabled=false}return}if(b.dataset.detail){studentDetail(b.dataset.detail);return}switch(b.dataset.action){case'choose':openStudents();break;case'startQuiz':startQuiz();break;case'submitQuiz':await submitQuiz();break;case'retrySave':b.disabled=true;await saveQuiz();b.disabled=false;if(quiz.saved)b.remove();break;case'redo':if(quiz&&!quiz.saved&&config.apiUrl&&!confirm('Kết quả hiện tại chưa được gửi cho GVCN. Em muốn bỏ kết quả này và luyện lại?'))break;quiz=null;startQuiz();break;case'refresh':await teacherDashboard();break;case'logout':teacherToken='';teacherRoster=[];events=[];render();break;case'export':exportCSV();break;}});
window.addEventListener('beforeunload',e=>{if(quiz&&!quiz.saved){saveDraft();e.preventDefault();e.returnValue=''}});
render();
