'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const data=window.CLASS_DATA;
const subjects=[
 {id:'toan',name:'Toán',icon:'π',color:'#295eb1',tint:'#eaf0ff',desc:'Đề cương để đọc, tải về và tự ôn tập.',resources:[['toan-dc','Đề cương Toán','toan-de-cuong.pdf','PDF']]},
 {id:'van',name:'Ngữ Văn',icon:'V',color:'#a34956',tint:'#faedf0',desc:'Đề cương, đọc hiểu, hướng dẫn viết và bài văn tham khảo.',resources:[['van-dc','Đề cương Ngữ Văn','van-de-cuong.docx','DOCX'],['van-lt','Đề luyện thêm','van-de-luyen.pdf','PDF'],["van-extra-1", "Mẫu viết đoạn văn nghị luận xã hội", "van-mau-doan-nlxh.pdf", "PDF"],["van-extra-2", "Công thức đọc hiểu Văn 10", "van-cong-thuc-doc-hieu.pdf", "PDF"],["van-extra-3", "Kho dẫn chứng nghị luận xã hội", "van-kho-dan-chung-nlxh.pdf", "PDF"],["van-extra-4", "Mẫu viết bài nghị luận văn học", "van-mau-bai-nlvh.pdf", "PDF"],["van-extra-5", "Đoạn văn, bài văn mẫu tham khảo", "van-bai-mau-tham-khao.pdf", "PDF"]]},
 {id:'anh',name:'Tiếng Anh',icon:'Aa',color:'#946624',tint:'#fbf3e4',desc:'Đề cương ôn tập và đề tham khảo số 2.',resources:[['anh-dc','Đề cương Tiếng Anh','anh-de-cuong.docx','DOCX'],['anh-de2','Đề tham khảo số 2','anh-de-2.docx','DOCX']]},
 {id:'li',name:'Vật Lí',icon:'v/t',color:'#345dc5',tint:'#e9efff',desc:'Làm 25 câu trực tiếp và đối chiếu đáp án sau khi nộp.',resources:[['li-de','Đề Vật Lí · Mã 1104','li-de-1104.docx','DOCX']]},
 {id:'hoa',name:'Hoá học',icon:'H₂',color:'#7c4db2',tint:'#f1eafb',desc:'Đề cương và hai bài luyện tập từ giáo viên bộ môn.',resources:[['hoa-dc','Đề cương Hoá học','hoa-de-cuong.docx','DOCX'],['hoa-c1','Luyện tập Chương 1','https://youngtest.vn/quiz/ukkJZ9','YOUNGTEST'],['hoa-c2','Luyện tập Chương 2','https://youngtest.vn/quiz/xfxMyp','YOUNGTEST']]},
 {id:'tin',name:'Tin học',icon:'</>',color:'#177f95',tint:'#e6f5f8',desc:'Tải đề cương và chủ động ôn lại kiến thức.',resources:[['tin-dc','Đề cương Tin học','tin-de-cuong.docx','DOCX']]}
];
let student=null,quiz=null,timer=null,toastTimer;
const date=v=>new Date(v).toLocaleString('vi-VN');
function toast(s){$('#toast').textContent=s;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',6500)}
function openStudents(){$('#studentsDialog').showModal()}
function setStudent(s){if(quiz&&student?.id!==s.id&&!confirm('Đổi học sinh sẽ đóng bài luyện hiện tại. Tiếp tục?'))return;quiz=null;student=s;$('#identity').textContent=s.name;$('#studentsDialog').close();render();toast('Đã chọn '+s.name)}
$('#identity').onclick=openStudents;$('#closeStudents').onclick=()=>$('#studentsDialog').close();
$('#studentList').innerHTML=data.students.map(s=>`<button class="studentbtn" data-student="${s.id}"><span>${s.id}</span>${esc(s.name)}</button>`).join('');
$('#studentList').onclick=e=>{const b=e.target.closest('[data-student]');if(b)setStudent(data.students.find(s=>s.id===b.dataset.student))};
function needStudent(){if(!student){openStudents();return false}return true}
function home(){return `<section class="welcome"><div><span class="eyebrow">LỚP 10IT · GIỮA HỌC KÌ I</span><h1>10IT - Ôn tập giữa Học Kì I</h1><p>${student?'Chào '+esc(student.name)+'. Chọn một môn để bắt đầu buổi ôn tập hôm nay.':'Một nơi cho đề cương, tài liệu và bài luyện của lớp mình. Chọn tên học sinh của em rồi bắt đầu ôn tập.'}</p><button class="primary" data-action="choose">${student?'Đổi học sinh':'Chọn tên để vào học'}</button></div><div class="welcome-side"><strong>16 <span style="font-size:18px;font-weight:400">học sinh</span></strong><p>6 môn học · 1 mục tiêu</p><small>Ôn từng phần, chắc từng bước.</small></div></section><div class="sectionhead"><h2>Hôm nay em ôn môn nào?</h2><span class="pill">Tài liệu từ giáo viên</span></div><section class="subjects">${subjects.map(s=>`<article class="subject ${s.id==='li'?'physics':''}" style="--accent:${s.color};--tint:${s.tint}"><div class="subject-top"><span class="subject-icon" aria-hidden="true">${esc(s.icon)}</span><span class="pill">${s.id==='li'?'Luyện trực tuyến':s.resources.length?'Tài liệu ôn tập':'Sẽ cập nhật'}</span></div><h3>${s.name}</h3><p>${s.desc}</p><div class="subject-foot"><span>${s.id==='li'?'25 câu · Mã 1104':s.resources.length?s.resources.length+' tài liệu / bài luyện':'Chưa có tài liệu'}</span><span>${s.id==='li'?'40 phút gợi ý':''}</span></div><a class="${s.id==='li'?'primary':'secondary'}" href="#subject/${s.id}">${s.resources.length?'Vào ôn tập':'Xem môn học'}</a></article>`).join('')}</section>`}
function subjectPage(id){const s=subjects.find(s=>s.id===id);if(!s)return home();return `<a class="back" href="#home">Quay lại các môn</a><span class="eyebrow" style="display:block">TÀI LIỆU & LUYỆN TẬP</span><h1>${s.name}</h1><p class="muted">${s.desc}</p>${s.id==='li'?`<section class="panel"><span class="pill">LÀM TRỰC TIẾP TRÊN WEB</span><h2 style="margin-top:12px">Vật Lí 10 · Mã đề 1104</h2><p>25 câu trắc nghiệm · Thời gian gợi ý 40 phút. Nộp bài để xem đúng/sai và đáp án từ giáo viên. Đây là bài tự luyện, không phải bài kiểm tra lấy điểm.</p><button class="primary" data-action="startQuiz">Bắt đầu luyện tập</button></section>`:''}<div class="resources">${s.resources.map(r=>`<article class="resource"><div><span class="eyebrow">${r[3]}</span><h3>${r[1]}</h3><p>${r[3]==='YOUNGTEST'?'Bài luyện do giáo viên bộ môn cung cấp':'Giữ nguyên tài liệu giáo viên cung cấp'}</p></div><div class="resource-actions"><a href="${r[2]}" target="_blank" rel="noopener noreferrer" data-resource="${r[0]}">${r[3]==='YOUNGTEST'?'Mở bài luyện':'Mở / tải tài liệu'}</a></div></article>`).join('')||'<div class="panel empty">Chưa có tài liệu.</div>'}</div>`}
function startQuiz(){if(!needStudent())return;quiz={answers:Array(25).fill(''),started:Date.now(),submitted:false};location.hash='quiz';render()}
function quizPage(){if(!quiz)return '<div class="panel empty"><h1>Bài luyện Vật Lí</h1><p>Chọn tên học sinh trước khi bắt đầu.</p><button class="primary" data-action="startQuiz">Bắt đầu luyện tập</button></div>';const n=quiz.answers.filter(Boolean).length;return `<a class="back" href="#subject/li">Quay lại môn Vật Lí</a><span class="eyebrow" style="display:block">VẬT LÍ · MÃ ĐỀ 1104</span><h1>${quiz.submitted?'Kết quả bài luyện':'Từng câu một, thật chắc kiến thức.'}</h1><p class="muted">${esc(student.name)} · 25 câu trắc nghiệm · Thời gian gợi ý 40 phút</p>${quiz.submitted?`<section class="result"><strong>${quiz.correct}/25 câu đúng</strong><p>${25-quiz.correct} câu sai hoặc chưa trả lời · ${Math.floor(quiz.duration/60)} phút ${quiz.duration%60} giây</p><p>Kết quả chỉ hiển thị trong buổi luyện này.</p><div class="actions"><button class="secondary" data-action="redo">Luyện lại</button></div></section><div class="notice">Đáp án đối chiếu từ file giáo viên, mã 1104. Chưa có lời giải chi tiết. Đáp án không thay thế việc đọc lại kiến thức.</div>`:''}<div class="quiz-layout"><div class="quiz-main">${data.groups.map((g,i)=>`<section><h2>Nhóm câu ${g.questions[0].id}–${g.questions.at(-1).id}</h2><div class="intro">${g.intro}</div>${g.questions.map(q=>`<fieldset class="question" id="question-${q.id}" ${quiz.submitted?'disabled':''}><legend>Câu ${q.id}. ${q.text}</legend><div class="answers">${q.options.map(o=>`<label class="option ${quiz.submitted?(o.label===data.key[q.id-1]?'correct':quiz.answers[q.id-1]===o.label?'wrong':''):''}"><input type="radio" name="q${q.id}" value="${o.label}" data-q="${q.id}" ${quiz.answers[q.id-1]===o.label?'checked':''}><span><b>${o.label}.</b> ${o.text}</span></label>`).join('')}</div>${quiz.submitted?`<p class="review-note">${quiz.answers[q.id-1]===data.key[q.id-1]?'Đúng':'Chưa đúng'} · Em chọn: ${quiz.answers[q.id-1]||'Chưa trả lời'} · Đáp án: <strong>${data.key[q.id-1]}</strong></p>`:''}</fieldset>`).join('')}</section>`).join('')}</div><aside class="quiz-side panel"><span class="eyebrow">${quiz.submitted?'ĐÃ NỘP BÀI':'THỜI GIAN ĐÃ LÀM'}</span><div class="clock" id="clock">00:00</div><p class="muted" id="answeredCount">Đã trả lời ${n}/25 câu</p><div class="progressbar"><span id="quizBar" style="width:${n*4}%"></span></div><div class="qnav">${Array.from({length:25},(_,i)=>`<a href="#question-${i+1}" data-jump="${i+1}" class="${quiz.answers[i]?'answered':''}">${i+1}</a>`).join('')}</div>${!quiz.submitted?'<button class="primary" data-action="submitQuiz">Nộp bài & xem đáp án</button><small class="muted">Bài làm chỉ được giữ khi trang đang mở. Thời gian là gợi ý, không tự động nộp.</small>':'<a href="#subject/li">Về môn Vật Lí</a>'}</aside></div>`}
function clockTick(){if(!quiz||!$('#clock'))return;const secs=quiz.submitted?quiz.duration:Math.floor((Date.now()-quiz.started)/1000);$('#clock').textContent=String(Math.floor(secs/60)).padStart(2,'0')+':'+String(secs%60).padStart(2,'0')}
async function submitQuiz(){if(!quiz||quiz.submitted)return;const missing=quiz.answers.filter(a=>!a).length;if(!confirm(missing?`Còn ${missing} câu chưa trả lời. Em muốn nộp bài và xem đáp án?`:'Nộp bài và xem đáp án?'))return;quiz.duration=Math.max(0,Math.floor((Date.now()-quiz.started)/1000));quiz.correct=quiz.answers.filter((a,i)=>a===data.key[i]).length;quiz.submitted=true;render();window.scrollTo(0,0);}
function render(){clearInterval(timer);const route=location.hash.slice(1)||'home';let html;if(route.startsWith('subject/'))html=subjectPage(route.split('/')[1]);else if(route==='quiz'){html=quizPage();timer=setInterval(clockTick,1000)}else html=home();$('#main').innerHTML=html;clockTick();}
window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#question-'))return;render()});
$('#main').addEventListener('change',e=>{if(e.target.matches('[data-q]')&&quiz&&!quiz.submitted){quiz.answers[+e.target.dataset.q-1]=e.target.value;const n=quiz.answers.filter(Boolean).length;$('#answeredCount').textContent=`Đã trả lời ${n}/25 câu`;$('#quizBar').style.width=n*4+'%';document.querySelector(`[data-jump="${e.target.dataset.q}"]`)?.classList.add('answered')}});
$('#main').addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.jump){e.preventDefault();$('#question-'+b.dataset.jump)?.scrollIntoView({behavior:'smooth'});return}switch(b.dataset.action){case'choose':openStudents();break;case'startQuiz':startQuiz();break;case'submitQuiz':submitQuiz();break;case'redo':startQuiz();break;}});
render();
